;[
  {
    counter: 1,
    finally: '1',
    futureCovDeltaTsLayerName: 'coverage_0_future_v184',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_voice/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_voice/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors.',
      'OK outdoors. Patchy indoors.',
      'Good outdoors. Patchy indoors.',
      'Good outdoors. OK indoors.',
      'Good indoors and outdoors.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Making calls, sending texts, using email on your phone.',
    layerIcon: 'sbuzz_2g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerLegendFuture: [
      {
        c: '#AA008888',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#AA00B33C',
        l: 'Good Outdoors',
      },
    ],
    layerName: 'Voice, text and email (2G)',
    layerNameMobile: '2G',
    layerOpacity: 0.6,
    miscCovDeltaTsLayerName: 'coverage_0_delta_v184',
    style: 'o2_uk_v184_voice',
    wizButton1Link: ['https://www.o2.co.uk/getupdates?lte', 'https://www.o2.co.uk/getupdates?lte', '', '', '', ''],
    wizButton1Text: ['Register your interest', 'Register your interest', '', '', '', ''],
    wizButton2Text: ['', '', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up'],
    wizLayerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors.',
      'OK outdoors. Patchy indoors.',
      'Good outdoors. Patchy indoors.',
      'Good outdoors. OK indoors.',
      'Good indoors and outdoors.',
    ],
    wizLayerDescription: 'Seamless connectivity and mobile internet.',
    wizLayerName: 'Mobile Internet (4G)',
    wizLayerTextBlock1: [
      "Why not try another postcode or town? Remember that 4G will be most useful when you're out and about, so if you've tried your home address, try work as well.",
      "We're still working on getting 4G here. But we're working towards 98% of the UK having 4G coverage by 2017. Register your interest and we'll let you know when 4G is coming your way.",
      'There is some 4G coverage in this area but not much.  However, as we work towards getting 4G coverage to 98% of the UK by 2017, it will improve.',
      '4G coverage is alright here and as we work towards getting 4G coverage to 98% of the UK by 2017, it will only get better.',
      '',
      '',
    ],
    wizLayerTextBlock2: [
      "Don't worry if there's no coverage near you at the moment - we're working on getting 4G to 98% of the UK. Register your interest and we'll let you know when 4G is coming your way.",
      '',
      '',
      '',
      '',
      '',
    ],
    wizResultTitles: [
      'Sorry, no 4G coverage here',
      '4G coverage is poor here',
      "4G coverage isn't great here",
      '4G coverage is OK here',
      'There is good 4G coverage here',
      'There is excellent 4G coverage here',
    ],
    zoomRangeFrom: 1,
    zoomRangeTo: 18,
  },
  {
    counter: 2,
    finally: '1',
    futureCovDeltaTsLayerName: 'coverage_1_future_v184',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_data/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_data/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors. Not good for mobile broadband.',
      'OK outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. OK indoors. Not good for mobile broadband.',
      'Good indoors and outdoors. Good for mobile broadband.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Fast networking. For smartphones, dongles and tablets.',
    layerIcon: 'sbuzz_3g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerLegendFuture: [
      {
        c: '#AA008888',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#AA00B33C',
        l: 'Good Outdoors',
      },
    ],
    layerName: 'Mobile internet and voice (3G 2100 only)',
    layerNameMobile: '3G (2100)',
    layerOpacity: 0.6,
    miscCovDeltaTsLayerName: 'coverage_1_delta_v184',
    style: 'o2_uk_v184_data',
    swapWithLayer: '2',
    swapWithLayerInfoLink: 'http://www.o2.co.uk/network/3g2100',
    swapWithLayerInfoLinkTarget: '',
    swapWithLayerInfoLinkText: '',
    swapWithLayerIntro: '',
    swapWithLayerText: '&lt; Back',
    wizButton1Link: ['https://www.o2.co.uk/getupdates?lte', 'https://www.o2.co.uk/getupdates?lte', '', '', '', ''],
    wizButton1Text: ['Register your interest', 'Register your interest', '', '', '', ''],
    wizButton2Text: ['', '', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up'],
    wizLayerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors.',
      'OK outdoors. Patchy indoors.',
      'Good outdoors. Patchy indoors.',
      'Good outdoors. OK indoors.',
      'Good indoors and outdoors.',
    ],
    wizLayerDescription: 'Seamless connectivity and mobile internet.',
    wizLayerName: 'Mobile Internet (4G)',
    wizLayerTextBlock1: [
      "Why not try another postcode or town? Remember that 4G will be most useful when you're out and about, so if you've tried your home address, try work as well.",
      "We're still working on getting 4G here. But we're working towards 98% of the UK having 4G coverage by 2017. Register your interest and we'll let you know when 4G is coming your way.",
      'There is some 4G coverage in this area but not much.  However, as we work towards getting 4G coverage to 98% of the UK by 2017, it will improve.',
      '4G coverage is alright here and as we work towards getting 4G coverage to 98% of the UK by 2017, it will only get better.',
      '',
      '',
    ],
    wizLayerTextBlock2: [
      "Don't worry if there's no coverage near you at the moment - we're working on getting 4G to 98% of the UK. Register your interest and we'll let you know when 4G is coming your way.",
      '',
      '',
      '',
      '',
      '',
    ],
    wizResultTitles: [
      'Sorry, no 4G coverage here',
      '4G coverage is poor here',
      "4G coverage isn't great here",
      '4G coverage is OK here',
      'There is good 4G coverage here',
      'There is excellent 4G coverage here',
    ],
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 3,
    finally: '1',
    futureCovDeltaTsLayerName: 'coverage_2_future_v184',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_datacombined/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_datacombined/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors. Not good for mobile broadband.',
      'OK outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. OK indoors. Not good for mobile broadband.',
      'Good indoors and outdoors. Good for mobile broadband.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Fast networking. For smartphones, dongles and tablets.',
    layerIcon: 'sbuzz_3g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerLegendFuture: [
      {
        c: '#AA008888',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#AA00B33C',
        l: 'Good Outdoors',
      },
    ],
    layerName: 'Mobile internet and voice (3G)',
    layerNameMobile: '3G',
    layerOpacity: 0.6,
    miscCovDeltaTsLayerName: 'coverage_2_delta_v184',
    style: 'o2_uk_v184_datacombined',
    swapWithLayer: '1',
    swapWithLayerInfoLink: 'http://www.o2.co.uk/network/3g2100',
    swapWithLayerInfoLinkTarget: '',
    swapWithLayerInfoLinkText: '<div class="sbuzz_info_icon"></div>',
    swapWithLayerIntro: "Some phones won't work on this 3G 900 frequency.",
    swapWithLayerText: 'Coverage information for phones that work on a different 3G frequency &gt;',
    wizButton1Link: ['https://www.o2.co.uk/getupdates?lte', 'https://www.o2.co.uk/getupdates?lte', '', '', '', ''],
    wizButton1Text: ['Register your interest', 'Register your interest', '', '', '', ''],
    wizButton2Text: ['', '', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up', 'Continue 4G set-up'],
    wizLayerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors.',
      'OK outdoors. Patchy indoors.',
      'Good outdoors. Patchy indoors.',
      'Good outdoors. OK indoors.',
      'Good indoors and outdoors.',
    ],
    wizLayerDescription: 'Seamless connectivity and mobile internet.',
    wizLayerName: 'Mobile Internet (4G)',
    wizLayerTextBlock1: [
      "Why not try another postcode or town? Remember that 4G will be most useful when you're out and about, so if you've tried your home address, try work as well.",
      "We're still working on getting 4G here. But we're working towards 98% of the UK having 4G coverage by 2017. Register your interest and we'll let you know when 4G is coming your way.",
      'There is some 4G coverage in this area but not much.  However, as we work towards getting 4G coverage to 98% of the UK by 2017, it will improve.',
      '4G coverage is alright here and as we work towards getting 4G coverage to 98% of the UK by 2017, it will only get better.',
      '',
      '',
    ],
    wizLayerTextBlock2: [
      "Don't worry if there's no coverage near you at the moment - we're working on getting 4G to 98% of the UK. Register your interest and we'll let you know when 4G is coming your way.",
      '',
      '',
      '',
      '',
      '',
    ],
    wizResultTitles: [
      'Sorry, no 4G coverage here',
      '4G coverage is poor here',
      "4G coverage isn't great here",
      '4G coverage is OK here',
      'There is good 4G coverage here',
      'There is excellent 4G coverage here',
    ],
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 4,
    finally: '1',
    futureCovDeltaTsLayerName: 'coverage_3_future_v184',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_lte/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_lte/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we do not have coverage here.',
      'Patchy outdoors. Patchy indoors. Not good for mobile broadband.',
      'OK outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. Patchy indoors. Not good for mobile broadband.',
      'Good outdoors. OK indoors. Not good for mobile broadband.',
      'Good indoors and outdoors. Good for mobile broadband.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Seamless connectivity and mobile internet.',
    layerIcon: 'sbuzz_4g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerLegendFuture: [
      {
        c: '#AA008888',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#AA00B33C',
        l: 'Good Outdoors',
      },
    ],
    layerName: 'Mobile Internet (4G)',
    layerNameMobile: '4G',
    layerOpacity: 0.6,
    miscCovDeltaTsLayerName: 'coverage_3_delta_v184',
    style: 'o2_uk_v184_lte',
    wizButton1Link: ['https://www.o2.co.uk/getupdates?lte', 'https://www.o2.co.uk/getupdates?lte', '', '', '', ''],
    wizButton1Text: ['Register for updates', 'Register for updates', '', '', '', ''],
    wizButton2Text: [
      'Continue 4G set-up',
      'Continue 4G set-up',
      'Continue 4G set-up',
      'Continue 4G set-up',
      'Continue 4G set-up',
      'Continue 4G set-up',
    ],
    wizLayerBarDescriptions: [
      "We don't have 4G here at the moment, but register for updates and we'll let you know when 4G is coming to you.",
      'Patchy outdoors. Patchy indoors.',
      'OK outdoors. Patchy indoors.',
      'Good outdoors. Patchy indoors.',
      'Good outdoors. OK indoors.',
      'Good indoors and outdoors.',
    ],
    wizLayerDescription: 'Seamless connectivity and mobile internet.',
    wizLayerName: 'Mobile Internet (4G)',
    wizLayerTextBlock1: [
      "Why not try another postcode or town? Remember that 4G will be most useful when you're out and about, so if you've tried your home address, try work as well.",
      "We're still working on getting 4G here. But we're working towards 98% of the UK having 4G coverage by 2017. Register your interest and we'll let you know when 4G is coming your way.",
      'There is some 4G coverage in this area but not much.  However, as we work towards getting 4G coverage to 98% of the UK by 2017, it will improve.',
      '4G coverage is alright here and as we work towards getting 4G coverage to 98% of the UK by 2017, it will only get better.',
      '',
      '',
    ],
    wizLayerTextBlock2: [
      "Don't worry if there's no coverage near you at the moment - we're working on getting 4G to 98% of the UK. Register your interest and we'll let you know when 4G is coming your way.",
      '',
      '',
      '',
      '',
      '',
    ],
    wizResultTitles: [
      'Sorry, no 4G coverage here',
      '4G coverage is poor here',
      "4G coverage isn't great here",
      '4G coverage is OK here',
      'There is good 4G coverage here',
      'There is excellent 4G coverage here',
    ],
    zoomRangeFrom: 1,
    zoomRangeTo: 18,
  },
  {
    counter: 5,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_volte/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_volte/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, We do not have 4G calling available in this area.',
      'Patchy outdoors. Patchy indoors. Not good for 4G calling.',
      'OK outdoors. Patchy indoors. Not good for 4G calling.',
      'Good outdoors. Patchy indoors. Not good for 4G calling.',
      'Good outdoors. OK indoors. Not good for 4G calling.',
      'Good indoors and outdoors. Good for 4G calling.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Crystal-clear voice calls over 4G.',
    layerIcon: 'sbuzz_4g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerName: '4G calling',
    layerNameMobile: '4G calling',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_volte',
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 6,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_5g/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_5g/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry. We do not have 5G coverage at this location.',
      'Patchy outdoor coverage for 5G.',
      'Patchy outdoor coverage for 5G.',
      'Good outdoor coverage for 5G.',
      'Good outdoor coverage for 5G.',
      'Good outdoor coverage for 5G. Limited indoor coverage for 5G.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Seamless connectivity and mobile internet with faster speeds',
    layerIcon: 'sbuzz_5g',
    layerLegend: [
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerName: 'Mobile Internet (5G)',
    layerNameMobile: '5G',
    layerOpacity: 0.6,
    searchZoom: 15,
    style: 'o2_uk_v184_5g',
    zoomRangeFrom: 13,
    zoomRangeTo: 18,
  },
  {
    counter: 7,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_sky_5g/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_sky_5g/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry. We do not have 5G coverage at this location.',
      'Patchy outdoor coverage for 5G.',
      'Patchy outdoor coverage for 5G.',
      'Good outdoor coverage for 5G.',
      'Good outdoor coverage for 5G.',
      'Good outdoor coverage for 5G. Limited indoor coverage for 5G.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: '',
    layerIcon: 'sbuzz_5g',
    layerLegend: [
      {
        c: '#FF90D66C',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerName: 'Mobile Internet (5G)',
    layerNameHealth: '<span>(5G)</span> Seamless connectivity and mobile internet with faster speeds',
    layerNameMobile: '5G',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_sky_5g',
    zoomRangeFrom: 13,
    zoomRangeTo: 18,
  },
  {
    counter: 8,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_sky_4g/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_sky_4g/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we don’t have any coverage here.',
      'Patchy coverage in your home and outside.',
      'OK coverage outside, but patchy in your home.',
      'Good coverage outside, but patchy in your home.',
      'Good coverage outside and OK in your home.',
      'Good coverage in your home and outside.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: '',
    layerIcon: 'sbuzz_4g',
    layerLegend: [
      {
        c: '#FF65A85C',
        l: 'Good in/outdoors',
      },
      {
        c: '#FF90D66C',
        l: 'Good outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No coverage',
      },
    ],
    layerName: 'Superfast mobile internet, calls and texts',
    layerNameHealth: '<span>(4G)</span> Superfast mobile internet, calls and texts',
    layerNameMobile: '4G',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_sky_4g',
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 9,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_sky_volte/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_sky_volte/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we don’t have any coverage here.',
      'Patchy coverage in your home and outside. Not good for 4G calling. ',
      'OK coverage outside, but patchy in your home. Not good for 4G calling. ',
      'Good coverage outside, but patchy in your home. Not good for 4G calling. ',
      'Good coverage outside and OK in your home. Not good for 4G calling. ',
      'Good coverage in your home and outside. Good for 4G calling.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: '',
    layerIcon: 'sbuzz_4gc',
    layerLegend: [
      {
        c: '#FF65A85C',
        l: 'Good in/outdoors',
      },
      {
        c: '#FF90D66C',
        l: 'Good outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No coverage',
      },
    ],
    layerName: '4G Calling',
    layerNameHealth: '<span>(4G Calling)</span> Crystal-clear voice calls over 4G',
    layerNameMobile: '4G Calling',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_sky_volte',
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 10,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_sky_3g/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_sky_3g/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we don’t have any coverage here.',
      'Patchy coverage in your home and outside.',
      'OK coverage outside, but patchy in your home.',
      'Good coverage outside, but patchy in your home.',
      'Good coverage outside and OK in your home.',
      'Good coverage in your home and outside.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: '',
    layerIcon: 'sbuzz_3g',
    layerLegend: [
      {
        c: '#FF65A85C',
        l: 'Good in/outdoors',
      },
      {
        c: '#FF90D66C',
        l: 'Good outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No coverage',
      },
    ],
    layerName: 'Mobile internet, calls and texts',
    layerNameHealth: '<span>(3G)</span> Mobile internet, calls and texts',
    layerNameMobile: '3G',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_sky_3g',
    zoomRangeFrom: 11,
    zoomRangeTo: 18,
  },
  {
    counter: 11,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_sky_2g/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_sky_2g/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, we don’t have any coverage here.',
      'Patchy coverage in your home and outside.',
      'OK coverage outside, but patchy in your home.',
      'Good coverage outside, but patchy in your home.',
      'Good coverage outside and OK in your home.',
      'Good coverage in your home and outside.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: '',
    layerIcon: 'sbuzz_2g',
    layerLegend: [
      {
        c: '#FF65A85C',
        l: 'Good in/outdoors',
      },
      {
        c: '#FF90D66C',
        l: 'Good outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No coverage',
      },
    ],
    layerName: 'Calls and texts',
    layerNameHealth: '<span>(2G)</span> Calls and texts',
    layerNameMobile: '2G',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_sky_2g',
    zoomRangeFrom: 1,
    zoomRangeTo: 18,
  },
  {
    counter: 12,
    finally: '1',
    imageHeight: 256,
    imageUriGoogle: 'https://68aa7b45-tiles.spatialbuzz.net/tiles/o2_uk-v184/styles/o2_uk_v184_ltem/{z}/{x}/{y}.png',
    imageUriMicrosoft:
      'https://cdn.spatialbuzz.com/maps/tiles_o2_uk/tiles.py/o2_uk_v184_ltem/{quadkey}.png?version=184&InvalidateCache={invalidate}',
    imageUriSubdomains: 'maps,t0,t1,t2',
    imageWidth: 256,
    layerBarDescriptions: [
      'Sorry, We do not have LTE-M available in this area.',
      'Patchy outdoors. Patchy indoors. Not good for LTE-M.',
      'OK outdoors. Patchy indoors. Not good for LTE-M.',
      'Good outdoors. Patchy indoors. Not good for LTE-M.',
      'Good outdoors. OK indoors. Not good for LTE-M.',
      'Good indoors and outdoors. Good for LTE-M.',
    ],
    layerBarUrls: [
      'images/bars0-31x31.gif',
      'images/bars1-31x31.gif',
      'images/bars2-31x31.gif',
      'images/bars3-31x31.gif',
      'images/bars4-31x31.gif',
      'images/bars5-31x31.gif',
    ],
    layerDescription: 'Data transmission over LTE-M.',
    layerIcon: 'sbuzz_4g',
    layerLegend: [
      {
        c: '#FF90CAE0',
        l: 'Good Indoors & Outdoors',
      },
      {
        c: '#FFF3D1AD',
        l: 'Good Outdoors',
      },
      {
        c: '#FFFFFFFF',
        l: 'No Service',
      },
    ],
    layerName: 'LTE-M',
    layerNameMobile: 'LTE-M',
    layerOpacity: 0.6,
    style: 'o2_uk_v184_ltem',
    zoomRangeFrom: 1,
    zoomRangeTo: 18,
  },
]
